### ISSUE TITLE
Support for LayerCAM

### ISSUE THREAD

**Issue by PengtaoJiang** [keisen/tf-keras-vis#66]
Hi, @keisen , 
   Our paper "LayerCAM: Exploring Hierarchical Class Activation Maps for Localization" is accepted by TIP recently, which can visualize the class activation maps from any CNN layer of an off-the-shelf network. Could you add our method to your popular repository for more people to try this method? Our method is a simple modification of Grad-CAM. It should easy to implement. Here is the [paper](https://ieeexplore.ieee.org/document/9462463) and [code](https://github.com/PengtaoJiang/LayerCAM). Hope for your reply.

**Comment by keisen** [comment]
@PengtaoJiang , Thank you for sharing your great work!
I will read the paper and attempt to implement it!

However, before that, I have a question to ask about [the license of LayerCAM](https://github.com/PengtaoJiang/LayerCAM#license) just in case.
When our users commercially use LayerCAM via tf-keras-vis without getting permission, is this case a license violation?
If so, please do NOT allow us to incorporate LayerCAM into tf-keras-vis.
Because tf-keras-vis's license is MIT and we want our users to use it without worrying about whether it's commercial or not.

Thanks!

**Comment by PengtaoJiang** [comment]
Thanks for reminding me. I remove the license limit. Any user via your popular repository will not wrong about the license limit.

**Comment by keisen** [comment]
@PengtaoJiang , Thank you for your quick response! I'm grad to hear that.

**Comment by keisen** [comment]
@PengtaoJiang , I'm sorry for the delay to implement it.
I've now merged `LayerCAM` module to `master` branch. It will be released as `v0.8.0` in a few days.

All the best!

**Comment by keisen** [comment]
If the code I implemented has any problem, please let me know.
